---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  vars:
    keycloak_admin_password: "redhat01!"
    rhn_username: 'ilago@redhat.com'
    rhn_password: 'Nananacho5266!'
    keycloak_offline_install: True
    keycloak_rhsso_enable: True
    #keycloak_rhsso_download_url: "https://<internal-nexus.private.net>/<path>/<to>/rh-sso-x.y.z-server-dist.zip"
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.keycloak
  roles:
    - middleware_automation.redhat_csp_download.redhat_csp_download
    - middleware_automation.keycloak.keycloak
